### ISSUE TITLE
Can I push it into Chum? 

### ISSUE THREAD

**Issue by Dracks** [sargo-devel/harbour-searchnemo#11]
I will like to push a new version into chum, to make this app available to everybody (that has chum installed) Is it fine? I can fork and merge any changes needed?

**Comment by sargo-devel** [comment]
Thank you for adopting this app to chum. I hope it will be still useful. By the way, is it possible to browse available applications in chum from the web browser?

**Comment by Dracks** [comment]
tecnically is not addopted, I only modify and build it. (I can if needed modify it) But maybe will be better to move it to the community the project? 

Mmm... maybe here: https://build.sailfishos.org/project/show/sailfishos:chum ?
