### ISSUE TITLE
 GUI beautification

### ISSUE THREAD

**Issue by eson57** [sargo-devel/harbour-searchnemo#3]
Hi,
Thanks for the update. This app quickly became one of the most important for me. 
There was just one thing that bothered my aesthetic sense. A one liner space between the top text and the input box (my yellow line) would make it both easier to read, and a better look, don't you think?

Thanks again
Åke

![screenshot-16-06-23-07-52-10](https://cloud.githubusercontent.com/assets/2996154/16293338/6f6f4100-3919-11e6-95d6-e4fce1b68525.png)

**Comment by sargo-devel** [comment]
My intention was to keep the entry field closer to preceding description then to next options, but maybe too close...
No problem, I will add a space, but in the next release.
This version has already been sent to Jolla store.

**Comment by eson57** [comment]
Understood thanks!

**Comment by eson57** [comment]
One more thing...
There's something wrong with your Flattr account. This has been for at least two days. I've tried others accounts and they are fine.

![screenshot-16-06-23-10-28-45](https://cloud.githubusercontent.com/assets/2996154/16296823/4be70492-392e-11e6-8f17-8d5c6520b1d1.png)

**Comment by sargo-devel** [comment]
According to Flattr account.
I discussed with Flattr Support, they confirmed that there are problems with flattring Github urls. They are trying to solve it.
So, I decided to fix it myself and I shortened autosubmit url in Jolla store.
I made some tests, it looks like it is working now.

**Comment by eson57** [comment]
Well, it works if I browse your profile at flattr with my PC (which was not so easy to find), but the linked flattr button at Jolla Store still gives the same error button at flattr.

This is the only link where I can actually flattr...
https://flattr.com/profile/sargodevel
