### ISSUE TITLE
sqllite

### ISSUE THREAD

**Issue by GoAlexander** [sargo-devel/harbour-searchnemo#4]
This is off topic. Sorry that I write here but you didn`t mention your email address in your profile...  
I write app for Sailfish OS for exporting notes and bookmarks but I don`t know how to work with sqllite. I am newbie. As I see you use `sqlfileview.cpp` to parse notes but how can I get all notes one by one (as strings)?

I have a lot of questions... :))
We can continue our discussion by email: AlexanderDydychkin@yandex.ru

**Comment by sargo-devel** [comment]
Conversation continued by email
