### ISSUE TITLE
Please show path to file in matches list

### ISSUE THREAD

**Issue by Self-Perfection** [sargo-devel/harbour-searchnemo#5]
Now SearchNemo shows only file basename in list of matched files.

I use SearchNemo to search in my diary, which is divided in text files named as `%Y/%m/%d.txt`. Thus I can figure out only day of matched note in search results, but I don't see year and month. Well, I can tap matched file and unfold "File info" section to view full path, than return and repeat for each file, but this is extremely tedious.

I suppose ellipsis might be used to hide parts of the path to matched file in similar way that ellipsis is used now to hide part of basename which does not fit the screen.

**Comment by sargo-devel** [comment]
Hi,
I have just made some fixes to display full path of a file in a TXT-like sections of search results (commit: c1248234fc7f09e05d0a970975cdc842ba3301bd).
Example screenshot:
![l1](https://cloud.githubusercontent.com/assets/19689151/21141645/99111422-c13e-11e6-93f2-109d7abde85f.jpeg)
In my opinion the screen is slightly overloaded.
What do you think about it?

**Comment by Self-Perfection** [comment]
Looks good for me. It would be perfect if file path is more distinguishable from file contents. Maybe applying italics style to file contents line would improve readability?

Also order of results in txt section seems random. Is it possible to sort by fullpath or by file modification time?

**Comment by sargo-devel** [comment]
Finally, I decided to highlight lines which contain the searched text.
Example:
![i2](https://cloud.githubusercontent.com/assets/19689151/21200895/3a252cbc-c249-11e6-82c9-384af838d525.jpeg)
This will be added to next release, soon.
The search results are sorted alphabetically by fullpath. The deepest paths are at the begining.
Maybe in the future I will add some different sorting methods...
